// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import reflect "github.com/omniql/reflect"

// EnumerationGenerator is an autogenerated mock type for the EnumerationGenerator type
type EnumerationGenerator struct {
	mock.Mock
}

// ShouldGenerateString provides a mock function with given fields: path, fieldType
func (_m *EnumerationGenerator) ShouldGenerateString(path string, fieldType reflect.FieldContainer) (bool, error) {
	ret := _m.Called(path, fieldType)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, reflect.FieldContainer) bool); ok {
		r0 = rf(path, fieldType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, reflect.FieldContainer) error); ok {
		r1 = rf(path, fieldType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StringEnumeration provides a mock function with given fields: path, fieldType
func (_m *EnumerationGenerator) StringEnumeration(path string, fieldType reflect.FieldContainer) (string, error) {
	ret := _m.Called(path, fieldType)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, reflect.FieldContainer) string); ok {
		r0 = rf(path, fieldType)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, reflect.FieldContainer) error); ok {
		r1 = rf(path, fieldType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint16Enumeration provides a mock function with given fields: path, fieldType
func (_m *EnumerationGenerator) Uint16Enumeration(path string, fieldType reflect.FieldContainer) (uint16, error) {
	ret := _m.Called(path, fieldType)

	var r0 uint16
	if rf, ok := ret.Get(0).(func(string, reflect.FieldContainer) uint16); ok {
		r0 = rf(path, fieldType)
	} else {
		r0 = ret.Get(0).(uint16)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, reflect.FieldContainer) error); ok {
		r1 = rf(path, fieldType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Uint8Enumeration provides a mock function with given fields: path, fieldType
func (_m *EnumerationGenerator) Uint8Enumeration(path string, fieldType reflect.FieldContainer) (uint8, error) {
	ret := _m.Called(path, fieldType)

	var r0 uint8
	if rf, ok := ret.Get(0).(func(string, reflect.FieldContainer) uint8); ok {
		r0 = rf(path, fieldType)
	} else {
		r0 = ret.Get(0).(uint8)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, reflect.FieldContainer) error); ok {
		r1 = rf(path, fieldType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
